customer/api/urls.py
from django.urls import path, include

from customer.api.views import CreateCustomerAPI, ChangePasswordView, CreateStaffAPI

urlpatterns = [
    path('create-customer-api/', CreateCustomerAPI.as_view(), name='create_customer_api'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    path('create-staff-api/', CreateStaffAPI.as_view(), name='create_staff_api'),

]

customer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'customer'
urlpatterns = [
                  path('create-customer/', views.create_cutomer, name='create_customer'),
                  path('', views.home, name='home'),
                  path('login-customer/', views.login_customer, name='login_customer'),
                  path('logout-customer/', views.logout_customer, name='logout_customer'),
                  path('profile-customer/', views.profile_customer, name='profile_customer'),
                  path('customer-change-password/', views.customer_change_password, name='customer_change_password'),
                  path('customer-forgot-password/', views.customer_forgot_password, name='customer_forgot_password'),
                  path('customer-reset-password/', views.customer_reset_password, name='customer_reset_password'),
                  path('create-staff/', views.create_staff, name='create_staff'),
              ] + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)  # is this import of setting correct? check this later

order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
                  path('', views.order_basket, name='order_basket'),
                  path('order-submit/', views.order_submit, name='order_submit'),
                  path('order-confirm/', views.order_confirm, name='order_confirm'),
                  path('order-history/', views.order_history, name='order_history'),
                  path('order-history-latest/', views.order_history_latest, name='order_history_latest'),

              ] + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)  # is this import of setting correct? check this later

product/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'product'
urlpatterns = [
                  path('add-product/', views.add_product, name='add_product'),

              ]

project_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls')),
                  path('api/v1/', include('core.api.urls')),
                  path('customer/', include('customer.urls')),
                  path('product/', include('product.urls')),
                  path('order/', include('order.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    city_born = models.CharField(max_length=50)
    closest_friend = models.CharField(max_length=50)
    owner = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'




class Address(models.Model):
    address = models.CharField(max_length=150)
    customer = models.ManyToManyField(Customer)

    class Meta:
        verbose_name_plural = "Addresses"

    def __str__(self):
        return f'{self.address}'


class Discount(models.Model):
    discount_amount = models.CharField(max_length=5)
    discount_description = models.CharField(max_length=80)
    ACTIVE = 'active'
    DEACTIVE = 'deactive'
    choices = (
        (ACTIVE, 'active'),
        (DEACTIVE, 'deactive')
    )
    discount_status = models.CharField(max_length=30, choices=choices, db_index=True,
                                    default=ACTIVE,
                                    help_text='status of the discount')
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.discount_amount


from django.dispatch import receiver
from django.urls import reverse
from django_rest_passwordreset.signals import reset_password_token_created
from django.core.mail import send_mail


@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
    email_plaintext_message = "{}?token={}".format(reverse('password_reset:reset-password-request'),
                                                   reset_password_token.key)

    send_mail(
        # title:
        "Password Reset for {title}".format(title="Some website title"),
        # message:
        email_plaintext_message,
        # from:
        "noreply@somehost.local",
        # to:
        [reset_password_token.user.email]
    )


class Staff(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    personnel_code = models.CharField(max_length=50)
    owner = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Manager(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    owner = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

customer/api/views.py
from django.contrib.auth import get_user_model
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response
from rest_framework.views import APIView
User = get_user_model()
# from customer.models import Customer
#
#
from customer.api.serializers import CustomerSerializer, UserSerializer, StaffSerializer
from customer.models import Customer, Staff


class CreateCustomerAPI(APIView):

    def get(self, request, format=None):
        print('here')
        print(Customer.objects.all())
        serializer = CustomerSerializer(Customer.objects.all(), many=True)
        return Response(serializer.data)

    @csrf_exempt
    def post(self, request, format=None):
        print(request.data)
        # print(request.data['select_student'])
        # print('successsss')
        # student = Customer.objects.get(pk=request.data['select_student'])
        # for lesson_id in request.data['lessons']:
        #     lesson = Lesson.objects.get(pk=lesson_id)
        #     lesson.students.add(student)
        #     student.lessons.add(lesson)
        #     lesson.save()
        #     student.save()

        # serializer = StudentSerializer(Student.objects.all(), many=True)
        customer_data = dict(list(request.data.items())[1:6])
        user_data = dict(list(request.data.items())[6:8])
        customer_serializer = CustomerSerializer(data=customer_data)
        user_serializer = UserSerializer(data=user_data)
        if user_serializer.is_valid():
            print('user_serializer is valid!')
            user_created = User.objects.create_user(username=user_data['username'], password=user_data['password'], email=customer_data['email'])
            print(user_created)

        if customer_serializer.is_valid():
            print('customer_serializer is valid!')
            customer_created = customer_serializer.save()
            customer_created.owner = user_created
            customer_created.save()
        print(customer_data)
        print(user_data)
        # print(list(request.data.items()))
        return Response({})


from rest_framework import status
from rest_framework import generics
from rest_framework.response import Response
from django.contrib.auth.models import User
from .serializers import ChangePasswordSerializer
from rest_framework.permissions import IsAuthenticated

class ChangePasswordView(generics.UpdateAPIView):

    serializer_class = ChangePasswordSerializer
    model = User
    permission_classes = (IsAuthenticated,)

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Check old password
            if not self.object.check_password(serializer.data.get("old_password")):
                return Response({"old_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
            # set_password also hashes the password that the user will get
            self.object.set_password(serializer.data.get("new_password"))
            self.object.save()
            response = {
                'status': 'success',
                'code': status.HTTP_200_OK,
                'message': 'Password updated successfully',
                'data': []
            }

            return Response(response)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CreateStaffAPI(APIView):

    def get(self, request, format=None):
        print('here')
        print(Staff.objects.all())
        serializer = StaffSerializer(Staff.objects.all(), many=True)
        return Response(serializer.data)

    @csrf_exempt
    def post(self, request, format=None):
        print(request.data)
        # print(request.data['select_student'])
        # print('successsss')
        # student = Customer.objects.get(pk=request.data['select_student'])
        # for lesson_id in request.data['lessons']:
        #     lesson = Lesson.objects.get(pk=lesson_id)
        #     lesson.students.add(student)
        #     student.lessons.add(lesson)
        #     lesson.save()
        #     student.save()

        # serializer = StudentSerializer(Student.objects.all(), many=True)
        staff_data = dict(list(request.data.items())[1:5])
        user_data = dict(list(request.data.items())[5:7])
        staff_serializer = StaffSerializer(data=staff_data)
        user_serializer = UserSerializer(data=user_data)
        if user_serializer.is_valid():
            print('user_serializer is valid!')
            user_created = User.objects.create_user(username=user_data['username'], password=user_data['password'], email=staff_data['email'])
            print(user_created)

        if staff_serializer.is_valid() and user_serializer.is_valid():
            print('staff_serializer is valid!')
            staff_created = staff_serializer.save()
            staff_created.owner = user_created
            staff_created.save()
        print(staff_data)
        print(user_data)
        # print(list(request.data.items()))
        return Response({})

customer/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from customer.models import Customer, Manager, Staff
from product.models import Product, Category


def create_cutomer(request):
    if request.method == 'GET':
        print('create_customer in customer/views')
        return render(request, 'customer/register.html')
    if request.method == 'POST':
        print('create_customer in customer/views')
        return HttpResponse('hello')


def home(request):
    logged_in = ''
    try:
        if Manager.objects.filter(owner=request.user):
            logged_in = 'manager'
        elif Staff.objects.filter(owner=request.user):
            logged_in = 'staff'
        elif Customer.objects.filter(owner=request.user):
            logged_in = 'customer'
    except:
        logged_in = ''

    try:
        if request.GET['select_category'] == 'none':
            products = Product.objects.all()
        else:
            category = Category.objects.filter(pk=request.GET['select_category']).first()
            products = category.product_set.all()
    except:
        products = Product.objects.all()
    categories = Category.objects.all()

    return render(request, 'customer/home.html',
                  {'logged_in': logged_in, 'products': products, 'categories': categories})


from django.contrib.auth import get_user_model, authenticate, login, logout

User = get_user_model()


# Create your views here.


def login_customer(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('http://127.0.0.1:8000/customer/')
    return render(request, 'customer/login.html')


def logout_customer(request):
    logout(request)
    print('success')
    return render(request, 'customer/login.html')


def profile_customer(request):
    if request.method == "GET":
        customer = Customer.objects.filter(owner=request.user).first()
        return render(request, 'customer/profile.html', {'customer': customer})
    if request.method == "POST":
        customer = Customer.objects.filter(owner=request.user).first()
        customer.first_name = request.POST['first_name']
        customer.last_name = request.POST['last_name']
        customer.email = request.POST['email']
        customer.city_born = request.POST['city_born']
        customer.closest_friend = request.POST['closest_friend']
        customer.username = request.POST['username']
        customer.save()
        return render(request, 'customer/profile.html', {'customer': customer})


def customer_change_password(request):
    return render(request, 'customer/change_password.html')


def customer_forgot_password(request):
    return render(request, 'customer/forgot_password.html')


def customer_reset_password(request):
    return render(request, 'customer/reset_password.html')


def create_staff(request):
    if request.method == 'GET':
        print('create_staff in customer/views')
        return render(request, 'customer/register_staff.html')

customer/templates/customer/forgot_password.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Login</b></h5>
                        <form id="form" method="get" action="{% url 'customer:customer_reset_password' %}">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='email' id="email">
                                <label for="old_password">email</label>
                            </div>
                            <div class="d-grid">
                                <button id="submit"  class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">next
                                </button>
                            </div>
                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#submit").on('click', function () {
                $.ajax({
                    url: 'http://127.0.0.1:8000/api/v1/cutomer-api/password_reset/',
                    type: "POST",
                    dataType: 'json',
                    data: $("#form").serialize(),
                    success: function (result) {
                        console.log(result);
                    },
                    error: function (xhr, resp, text) {
                        console.log(xhr, resp, text);
                    }
                })
            });
        });

    </script>
{% endblock %}

customer/templates/customer/home.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
    {% if user.is_authenticated %}
        <a href="{% url 'customer:profile_customer' %}">
            <button type="button" class="btn navs-button">profile</button>
        </a>
        <a href="{% url 'customer:logout_customer' %}">
            <button type="button" class="btn navs-button">logout</button>
        </a>
        {% if logged_in == 'customer' %}

            <a href="{% url 'order:order_basket' %}">
                <button type="button" class="btn navs-button">my basket</button>
            </a>
            <a href="{% url 'order:order_history' %}">
                <button type="button" class="btn navs-button">order historty</button>
            </a>
        {% endif %}
        {% if logged_in == 'manager' %}

            <a href="{% url 'customer:create_staff' %}">
                <button type="button" class="btn navs-button">add staff</button>
            </a>
            <a href="{% url 'product:add_product' %}">
                <button type="button" class="btn navs-button">add product</button>
            </a>
        {% endif %}
        {% if logged_in == 'staff' %}
            <a href="{% url 'product:add_product' %}">
                <button type="button" class="btn navs-button">add product</button>
            </a>
        {% endif %}
    {% endif %}
    <a href="{% url 'customer:login_customer' %}">
        <button type="button" class="btn navs-button">Login</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <form method="get" id="customer-form" action="{% url 'customer:home' %}">

                <label> choose category</label>
                <select name="select_category">
                    <option value="none">none</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-primary btn-login text-uppercase fw-bold" id="submit"
                        type="submit">show categorized
                </button>
            </form>
        </div>
        <div class="row">
            {% for product in products %}

                <div class="card" style="width:30%">
                    <img class="card-img-top" src="{{ product.image.url }}" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <h4 class="card-title">{{ product.name }}</h4>
                        <h4 class="card-title">{{ product.price }} dollars</h4>
                        <p class="card-text">{{ product.description }}</p>

                        <button class="btn btn-primary btn-login" title="add"
                                id="add{{ product.id }}"></button>

                    </div>
                </div>



            {% endfor %}
        </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>
        {% for product in products %}
            $('#add{{ product.id }}').text('add');
            $('#add{{ product.id }}').click(function () {
                const url = "http://127.0.0.1:8000/api/v1/order-api/create-order-api/{{ product.id }}";
                $.ajax({
                    type: "GET",
                    url: url,
                    success: function () {
                        if ($('#add{{ product.id }}').text() === 'add') {
                            $('#add{{ product.id }}').text('remove');

                        } else if ($('#add{{ product.id }}').text() === 'remove') {
                            $('#add{{ product.id }}').text('add');
                        }
                    },
                });
            });
        {% endfor %}
    </script>
{% endblock %}

customer/templates/customer/login.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Login</b></h5>
                        <form action="{% url 'customer:login_customer' %}" method="post">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='username' id="username">
                                <label for="username">Username</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" name="password" id="password"
                                       placeholder="Password">
                                <label for="password">Password</label>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">log
                                    in
                                </button>
                            </div>
                            <div class="d-grid">
                                <a id="forgot-password" href="{% url 'customer:customer_forgot_password' %}">forgot password
                                </a>
                            </div>
                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}

customer/templates/customer/profile.html
{% extends 'customer/base.html' %}

{% block title %}WebBlog | Sign up{% endblock %}

{% block left_items_in_nav %}
    <a href="">
        <button type="button" class="btn navs-button">Login</button>
    </a>
{% endblock %}


{% block main %}

    <style>
        #short-time-msg {
            color: blue;
            background: lightblue;
            font-weight: bolder
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Sign up</b></h5>
                        <form method="post" id="customer-form" action="{% url 'customer:profile_customer'%}">
                            {% csrf_token %}

                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="first_name" id="first_name" value="{{ customer.first_name }}" required>

                                <label for="first_name">First Name</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="last_name" id="last_name" value="{{ customer.last_name }}" required>

                                <label for="last_name">Last Name</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" name="email" id="email" value="{{ customer.email }}">

                                <label for="email">Email</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="city_born" id="city_born" value="{{ customer.city_born }}">

                                <label for="phone">City Born (incase you forgot your password)</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="closest_friend" id="closest_friend" value="{{ customer.closest_friend }}">

                                <label for="phone">Your Closest Friend (incase you forgot your password)</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name="username" id="username" value="{{ customer.owner.username }}" required>

                                <label for="floatingInput">Username</label>
                            </div>



                            <div class="d-grid">
                                <button class="btn btn-primary btn-login text-uppercase fw-bold" id="submit"
                                        type="submit">Sign Up
                                </button>
                            </div>
                            <div class="d-grid">
                                <a href="{% url 'customer:customer_change_password' %}">change password
                                </button>
                            </div>
                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_footer %}{% endblock %}
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
{% endblock %}

customer/templates/customer/reset_password.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Login</b></h5>
                        <form id="form" method="get" action="{% url 'customer:login_customer'%}">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" name='password' id="password">
                                <label for="old_password">new password</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='token' id="token">
                                <label for="token">token (has been sent to email)</label>
                            </div>
                            <div class="d-grid">
                                <button id="submit" class="btn btn-primary btn-login text-uppercase fw-bold"
                                        type="submit">change password
                                </button>
                            </div>
                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#submit").on('click', function () {
                $.ajax({
                    url: 'http://127.0.0.1:8000/api/v1/cutomer-api/password_reset/confirm/',
                    type: "POST",
                    dataType: 'json',
                    data: $("#form").serialize(),
                    success: function (result) {
                        console.log(result);
                    },
                    error: function (xhr, resp, text) {
                        console.log(xhr, resp, text);
                    }
                })
            });
        });

    </script>
{% endblock %}