customer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'customer'
urlpatterns = [
                  path('create-customer/', views.create_cutomer, name='create_customer'),
                  path('', views.home, name='home'),
                  path('login-customer/', views.login_customer, name='login_customer'),
                  path('logout-customer/', views.logout_customer, name='logout_customer'),
                  path('profile-customer/', views.profile_customer, name='profile_customer'),
                  path('customer-change-password/', views.customer_change_password, name='customer_change_password'),
                  path('customer-forgot-password/', views.customer_forgot_password, name='customer_forgot_password'),
                  path('customer-reset-password/', views.customer_reset_password, name='customer_reset_password'),
                  path('create-staff/', views.create_staff, name='create_staff'),
              ] + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)  # is this import of setting correct? check this later

order/api/urls.py
from django.urls import path

from order.api.views import create_order_api

urlpatterns = [
    path('create-order-api/<int:ids>', create_order_api, name='create_order_api'),


]

order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
                  path('', views.order_basket, name='order_basket'),
                  path('order-submit/', views.order_submit, name='order_submit'),
                  path('order-confirm/', views.order_confirm, name='order_confirm'),
                  path('order-history/', views.order_history, name='order_history'),
                  path('order-history-latest/', views.order_history_latest, name='order_history_latest'),

              ] + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)  # is this import of setting correct? check this later

project_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls')),
                  path('api/v1/', include('core.api.urls')),
                  path('customer/', include('customer.urls')),
                  path('product/', include('product.urls')),
                  path('order/', include('order.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models

from customer.models import Customer
from product.models import Product


class Order(models.Model):
    products = models.ManyToManyField(Product)
    number_of_products = models.JSONField(blank=True, null=True)
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    CONFIRMED = 'confirmed'
    ON_WAY = 'on the way'
    DELIVERED = 'delivered'
    NOT_SELECTED = ''
    choices = (
        (CONFIRMED, 'confirmed'),
        (ON_WAY, 'on the way'),
        (DELIVERED, 'delivered'),
        (NOT_SELECTED, 'Not Selected'),
    )
    order_status = models.CharField(max_length=30, choices=choices, db_index=True,
                                    default=NOT_SELECTED,
                                    help_text='status of the order')
    date_submitted = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'order of {self.user}'


class OrderHistory(models.Model):
    order = models.OneToOneField(Order, on_delete=models.RESTRICT)
    user = models.ForeignKey(Customer, on_delete=models.RESTRICT)  # this might be wrong

    def __str__(self):
        return f'{self.order.__str__()}'

order/api/views.py
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView

from customer.models import Customer
from order.models import Order
from product.models import Product


@api_view(['GET', 'POST'])

def create_order_api(request, ids):
    if request.method == "GET":
        print(ids)
        print(request.user.username)
        print(request.user, type(request.user))
        product = Product.objects.filter(pk=ids).first()
        customer = Customer.objects.filter(owner=request.user).first()
        print(customer)


        # order = Order.objects.update_or_create(order_status='Not Selected', user=customer)
        # order = order.products.add(product)
        # print(order)
        # order.save()
        # print(order)
        #
        if Order.objects.filter(user=customer, order_status='Not Selected'):
            print('came here')
            order = Order.objects.filter(user=customer).first()

            # print(order.products.all())
            # order.products.add(product)
            # order.save()
            if product in order.products.all():
                order.products.remove(product)
                order.save()
            else:
                order.products.add(product)
                order.save()
        else:
            order = Order(order_status='Not Selected', user=customer)
            order.save()
            order.products.add(product)
            order.save()
    print(order.id)

    return Response({})
        # for post in Post.objects(id=post_id):
        #     if post.status == STATUS['ACTIVE']:
        #         # print('THIS IS ACTIVE')
        #         Post.objects(id=post_id).update(
        #             status=STATUS['DEACTIVE']
        #         )
        #     elif post.status == STATUS['DEACTIVE']:
        #         # print('THIS IS DEACTIVE')
        #         Post.objects(id=post_id).update(
        #             status=STATUS['ACTIVE']
        #         )
        # return render_template('posts_list.html')

order/views.py
from datetime import timedelta

from django.shortcuts import render, redirect
from django.utils.datetime_safe import date

from customer.models import Customer, Discount
from order.models import Order, OrderHistory


def order_basket(request):
    customer = Customer.objects.filter(owner=request.user).first()
    try:
        order = Order.objects.filter(user=customer).first()
        # print(order.order_status)
        # if order.order_status == 'Not Selected':
        #     pass
        # else:
        #     order= None
    except AttributeError:
        order = None
    print(customer)
    print(order)
    return render(request, 'order/order_basket.html', {'order': order})


def order_submit(request):
    my_dict = dict(request.POST)
    prices = [float(price) for price in my_dict['product_price']]
    numbers = [int(number) for number in my_dict['number_of_products']]
    total_price = []
    print(prices)
    print(numbers)
    print(prices[0] * numbers[0])
    for price, number in zip(prices, numbers):
        total_price.append(price * number)
    customer = Customer.objects.filter(owner=request.user).first()
    try:
        discount = Discount.objects.filter(customer=customer)
        discount = int(discount.discount_amount)
    except AttributeError:
        discount = 0

    print(discount)
    total_price_all = sum(total_price)
    return render(request, 'order/order_submit.html', {'total_price_all': total_price_all, 'discount': discount})


def order_confirm(request):
    customer = Customer.objects.filter(owner=request.user).first()
    order = Order.objects.filter(user=customer).first()
    order.order_status = 'confirmed'
    order.save()
    order_history = OrderHistory(order=order, user=customer)
    order_history.save()
    return redirect('http://127.0.0.1:8000/customer/')


def order_history(request):
    customer = Customer.objects.filter(owner=request.user).first()
    customer_order_history = OrderHistory.objects.filter(user=customer)
    return render(request, 'order/order_history.html', {'customer_order_history': customer_order_history})


def order_history_latest(request):
    customer = Customer.objects.filter(owner=request.user).first()
    enddate = date.today()
    startdate = enddate - timedelta(days=6)
    orders = Order.objects.filter(date_submitted__range=[startdate, enddate], user=customer)
    print(orders)
    return render(request, 'order/order_history_latest.html', {'orders': orders})

order/templates/order/order_basket.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>orders</b></h5>
                        <form action="{% url 'order:order_submit' %}" method="post">
                            {% csrf_token %}
                            {% for product in order.products.all %}
                                <p>{{ product.name }}</p>
                                <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='product_price' id="product_price" value="{{ product.price }}" readonly>
                                <label for="product_price">price</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="number" class="form-control" name="number_of_products" id="number_of_products" value="1" >
                                <label for="number_of_products" >number</label>
                            </div>
                            <div class="d-grid">
                                <hr class="my-4">
                            {% endfor %}

                                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">next
                                </button>
                            </div>
                            <div class="d-grid">

                            </div>
                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}

order/templates/order/order_history.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
    <a href="{% url 'order:order_history_latest' %}">
        <button type="button" class="btn navs-button">Latest orders</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>orders</b></h5>
                        {% for order_history in customer_order_history %}
                            <div class="form-floating mb-3">
                               <p>{{ order_history.order }}</p>
                            <p>{{ order_history.order }}</p>
                            </div>
                        {% endfor %}

                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}
{% block js %}

{% endblock %}

order/templates/order/order_history_latest.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>orders</b></h5>
                        {% for order in orders %}
                            <div class="form-floating mb-3">
                               <p>{{ order }}</p>
                            </div>
                        {% endfor %}

                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}
{% block js %}

{% endblock %}

order/templates/order/order_submit.html
{% extends 'customer/base.html' %}

{% load static %}

{% block css_href %}{% static 'users/css/login.css' %}{% endblock %}

{% block title %}WebBlog | Login{% endblock %}

{% block left_items_in_nav %}
    <a href="{% url 'customer:create_customer' %}">
        <button type="button" class="btn navs-button">Register</button>
    </a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>orders</b></h5>
                        <form action="{% url 'order:order_confirm' %}" method="post">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='total_price' id="total_price"
                                       value="{{ total_price_all }}" readonly>
                                <label for="product_price">total price</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='discount' id="discount"
                                       value="{{ discount }}" readonly>
                                <label for="product_price">discount</label>
                                <button class="btn btn-primary" type="button" id="discount_button">discount
                                    order
                                </button>
                            </div>


                            <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">submit order
                            </button>
                    </div>
                    <div class="d-grid">

                    </div>
                    <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}
{% block extra_footer %}<h1>hello5</h1>{% endblock %}
{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>
        $('#discount_button').click(function () {
            var price = ((100 - $('#discount').val())/100) * $('#total_price').val()
            $('#total_price').val(price) ;
           $('#discount_button').css("display", "none");
        });
    </script>
{% endblock %}